### ISSUE TITLE
Objetivos

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-guerra_naval#2]
Los objetivos del trabajo están sin cumplimentar.

**Comment by jhon7t** [comment]
hola con respecto  a eso cuales son ?
el menú

**Comment by oscarperpinan** [comment]
Los objetivos del trabajo los debéis proponer vosotros. Básicamente se trata de responder a la pregunta: "¿qué queremos conseguir con nuestro programa?".
Echad un vistazo a los repositorios de otros equipos.

**Comment by jhon7t** [comment]
ok

**Comment by oscarperpinan** [comment]
No olvidéis cerrar esta *issue* cuando la hayáis completado.
