### ISSUE TITLE
Ficheros con extensión .c

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-guerra_naval#3]
Todos los ficheros de código deben tener extensión ".c"

**Comment by oscarperpinan** [comment]
Insisto en este requerimiento. Todos los ficheros de código deben tener extensión ".c"

**Comment by jhon7t** [comment]
El .c se pone asi menu.c?

**Comment by oscarperpinan** [comment]
Si.

**Comment by jhon7t** [comment]
pero los de github no? o de mis archivos q estan en mi ordenador

**Comment by oscarperpinan** [comment]
Los dos. Si estás usando GitHub correctamente, la copia local (archivos de tu ordenador) y el repositorio, deben tener exactamente el mismo contenido.
