### ISSUE TITLE
Menú Inicio

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-guerra_naval#4]
- El menú de inicio que habéis implementado es extremadamente simple (dos opciones). Debéis realizar algo de mayor complejidad, y emplear bucles switch-case.
- Debéis cuidar la ortografía en general, y en particular en los mensajes mostrados en pantalla. Escribir "bienbenidos" nada más empezar el programa no es admisible.

**Comment by jhon7t** [comment]
vale.
