### ISSUE TITLE
Entrega final: logo del proyecto

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-guerra_naval#7]
Acompañando al código y a la documentación, debéis crear un logo que represente a vuestro proyecto. Este logo aparecerá en el [portfolio de proyectos de la web](https://aigora.github.io/#portfolio).

La imagen debe llamarse **logo.png** (en minúsculas), debe estar en formato PNG, y sus dimensiones deben ser: 400 x 289 píxeles. 

Esta imagen debe estar alojada en el nivel básico de vuestro repositorio (donde estén vuestros LICENSE y README.md). 

Si lo necesitáis, tenéis una [web](https://imageresizer.com/) para modificar el tamaño o formato de vuestra imagen.

**Debéis cerrar esta issue cuando deis por entregado el logo.**

**Comment by jhon7t** [comment]
Pero como lo coloco , es decir, dentro de un nuevo fichero como hago para subir la imagen ?

**Comment by oscarperpinan** [comment]
De forma idéntica a como has subido el resto de ficheros de tu repositorio. Lo pones en tu copia local, y luego commit+push.

**Comment by jhon7t** [comment]
En los ficheros yo subia codigo ahora con lo de la imagen no se dónde esté commit +push.
Yo no tengo github desktop

**Comment by jhon7t** [comment]
En los ficheros yo subia codigo ahora con lo de la imagen no se dónde esté commit +push.
Yo no tengo github desktop

**Comment by oscarperpinan** [comment]
Me sorprende este comentario a estas alturas del curso. Te animo a revisar la documentación sobre GitHub del [punto de inicio](https://github.com/aigora/punto_inicio/#punto-de-inicio).
En cualquier caso, he visto que ya has subido la imagen, aunque estás usando una extensión errónea. Debe ser **PNG**.
